name: pre-prod image creation / push to ghcr.io
on:
  release:
    types: [prereleased]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: dev

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      # https://github.com/docker/setup-qemu-action

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./exempt-ubi9-python3-dev.dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            "IMAGE_NAME=${{ github.repository }}"
            "IMAGE_TAG=${{ github.event.release.tag_name }}"
            
# "SOURCE_IMAGE=${{ vars.SOURCE_IMAGE }}"
# "SOURCE_IMAGE_TAG=${{ vars.SOURCE_IMAGE_TAG }}"
# "WORKING_DIR_NAME=${{ vars.WORKING_DIR }}"
# "SOURCE_IMAGE_LABEL=${{ vars.SOURCE_IMAGE_LABEL }}"
